services:
  - type: web
    name: peoconnect
    env: docker
    repo: https://github.com/Zhiyuan0904/PEOConnect
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    buildCommand: |
      composer install
      npm install
      npm run build
      php artisan config:cache
      php artisan migrate --force
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
