<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Survey Report</title>
  <style>
    body {
      font-family: 'Segoe UI', sans-serif;
      font-size: 14px;
      padding: 30px;
      color: #333;
    }
    h1, h2, h3 {
      color: #4072bc;
      margin-bottom: 5px;
    }
    hr {
      margin: 20px 0;
    }

    .center {
      text-align: center;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 10px;
    }

    th, td {
      border: 1px solid #d1d5db;
      padding: 8px 10px;
    }

    th {
      background-color: #f1f5f9;
      color: #4072bc;
      text-align: center;
    }

    td {
      text-align: center;
    }

    td.left {
      text-align: left;
    }

    .peo-list {
      margin-top: 30px;
    }

    .peo-list li {
      margin-bottom: 6px;
    }

    .footer {
      text-align: center;
      font-size: 12px;
      color: #888;
      margin-top: 40px;
    }
  </style>
</head>
<body>

  <!-- Header -->
  <h1 class="center">Survey Report</h1>
  <p class="center">Generated on {{ $generated_at }}</p>
  @if($year)
    <p class="center"><strong>Filtered Year:</strong> {{ $year }}</p>
  @endif
  <hr>

  <!-- Summary Cards in One Row -->
  <table width="100%" cellpadding="10" cellspacing="0" style="margin: 20px 0;">
    <tr>
      <td align="center" style="background-color: #f9fafb; border: 1px solid #e2e8f0; border-radius: 12px;">
        <h4 style="color: #4072bc; margin: 0;">Total Surveys</h4>
        <p style="font-size: 22px; font-weight: bold; margin: 0;">{{ $summary['total_surveys'] }}</p>
      </td>
      <td align="center" style="background-color: #f9fafb; border: 1px solid #e2e8f0; border-radius: 12px;">
        <h4 style="color: #4072bc; margin: 0;">Total Responses</h4>
        <p style="font-size: 22px; font-weight: bold; margin: 0;">{{ $summary['total_responded'] }}</p>
      </td>
      <td align="center" style="background-color: #f9fafb; border: 1px solid #e2e8f0; border-radius: 12px;">
        <h4 style="color: #4072bc; margin: 0;">Avg Completion</h4>
        <p style="font-size: 22px; font-weight: bold; margin: 0;">{{ $summary['avg_completion'] }}%</p>
      </td>
    </tr>
  </table>

  <!-- Table -->
  <h3>Survey Completion Breakdown</h3>
  <table>
    <thead>
      <tr>
        <th>Survey Title</th>
        <th>Target Role</th>
        <th>Total Users</th>
        <th>Responded</th>
        <th>Completion %</th>
      </tr>
    </thead>
    <tbody>
      @foreach($reportData as $r)
        <tr>
          <td class="left">{{ $r['survey_title'] }}</td>
          <td>{{ $r['target_role'] }}</td>
          <td>{{ $r['total'] }}</td>
          <td>{{ $r['responded'] }}</td>
          <td>{{ $r['percentage'] }}%</td>
        </tr>
      @endforeach
    </tbody>
  </table>

  <!-- PEO Section -->
  @if(count($topPeos))
    <h3 class="peo-list">Most Selected PEOs (from Curriculum)</h3>
    <ol>
      @foreach($topPeos as $peo)
        <li><strong>{{ $peo['code'] }}:</strong> {{ $peo['description'] }} <span style="color: #888;">({{ $peo['count'] }} selections)</span></li>
      @endforeach
    </ol>
  @endif

  <!-- Footer -->
  <hr>
  <p class="footer">Generated by PEOConnect – {{ \Carbon\Carbon::now()->year }}</p>

</body>
</html>
